### ISSUE TITLE
Issue when running docker

### ISSUE THREAD

**Issue by pontusvision** [sf11349/de_ssignment#2] opened 2024-05-07 19:55 UTC
Please help resolve this:

```
INFO:root:START the ETL pipeline run

INFO:root:Initiating Sparks instance
:: loading settings :: url = jar:file:/usr/local/spark-3.5.0-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/jovyan/.ivy2/cache
The jars for the packages stored in: /home/jovyan/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-cfcc130d-5de6-4d18-ac73-ee6c94f8e0d5;1.0
        confs: [default]
        found io.delta#delta-spark_2.12;3.1.0 in central
        found io.delta#delta-storage;3.1.0 in central
        found org.antlr#antlr4-runtime;4.9.3 in central
downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
        [SUCCESSFUL ] io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar (1344ms)
downloading https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar ...
        [SUCCESSFUL ] io.delta#delta-storage;3.1.0!delta-storage.jar (32ms)
downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
        [SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (104ms)
:: resolution report :: resolve 1484ms :: artifacts dl 1485ms
        :: modules in use:
        io.delta#delta-spark_2.12;3.1.0 from central in [default]
        io.delta#delta-storage;3.1.0 from central in [default]
        org.antlr#antlr4-runtime;4.9.3 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-cfcc130d-5de6-4d18-ac73-ee6c94f8e0d5
        confs: [default]
        3 artifacts copied, 0 already retrieved (5727kB/10ms)
24/05/07 19:44:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
INFO:root:Sparks instance ready

INFO:root: Extracting from source ....
+-------+----------+--------+--------+-----+
|OrderID|CustomerID| Product|Quantity|Price|
+-------+----------+--------+--------+-----+
|   1001|      C101|Widget A|      10| 25.5|
|   1002|      C102|Widget B|       5|18.75|
|   1003|      C103|Widget A|       8| 25.5|
|   1004|      C104|Widget C|      12| 30.0|
|   1005|      C105|Widget B|       3|18.75|
+-------+----------+--------+--------+-----+

INFO:root: - Number of records extracted: 5
INFO:root: Finished extracting from source.

INFO:root: Transforming ....
+-------+----------+--------+--------+-----+----------------+
|OrderID|CustomerID| Product|Quantity|Price|TotalOrderAmount|
+-------+----------+--------+--------+-----+----------------+
|   1001|      C101|Widget A|      10| 25.5|           255.0|
|   1002|      C102|Widget B|       5|18.75|           93.75|
|   1003|      C103|Widget A|       8| 25.5|           204.0|
|   1004|      C104|Widget C|      12| 30.0|           360.0|
|   1005|      C105|Widget B|       3|18.75|           56.25|
+-------+----------+--------+--------+-----+----------------+

INFO:root: - Number of records transformed: 5
INFO:root: Finished transformation.

INFO:root: Loading to Delta Table ....
24/05/07 19:44:46 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
24/05/07 19:44:50 ERROR Utils: Aborting task
java.io.IOException: Mkdirs failed to create file:/sf_de_assignment/data/sink/CustomerOrders/Product=Widget A (exists=false, cwd=file:/sf_de_assignment)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:515)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:500)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1195)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1175)
        at org.apache.parquet.hadoop.util.HadoopOutputFile.create(HadoopOutputFile.java:74)
        at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:347)
        at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:314)
        at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:484)
        at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:422)
        at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetOutputWriter.scala:36)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$$anon$1.newInstance(ParquetUtils.scala:490)
        at org.apache.spark.sql.execution.datasources.BaseDynamicPartitionDataWriter.renewCurrentWriter(FileFormatDataWriter.scala:298)
        at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.write(FileFormatDataWriter.scala:365)
        at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:85)
        at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
        at org.apache.spark.sql.delta.files.DeltaFileFormatWriter$.$anonfun$executeTask$1(DeltaFileFormatWriter.scala:430)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
        at org.apache.spark.sql.delta.files.DeltaFileFormatWriter$.executeTask(DeltaFileFormatWriter.scala:437)
        at org.apache.spark.sql.delta.files.DeltaFileFormatWriter$.$anonfun$executeWrite$2(DeltaFileFormatWriter.scala:274)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
        at org.apache.spark.scheduler.Task.run(Task.scala:141)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
24/05/07 19:44:50 ERROR DeltaFileFormatWriter: Job job_202405071944507520572064159862353_0017 aborted.
....
Caused by: java.io.IOException: Mkdirs failed to create file:/sf_de_assignment/data/sink/CustomerOrders/Product=Widget A (exists=false, cwd=file:/sf_de_assignment)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:515)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:500)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1195)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1175)
        at org.apache.parquet.hadoop.util.HadoopOutputFile.create(HadoopOutputFile.java:74)
        at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:347)
        at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:314)
        at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:484)
        at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:422)
        at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetOutputWriter.scala:36)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$$anon$1.newInstance(ParquetUtils.scala:490)
        at org.apache.spark.sql.execution.datasources.BaseDynamicPartitionDataWriter.renewCurrentWriter(FileFormatDataWriter.scala:298)
        at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.write(FileFormatDataWriter.scala:365)
        at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:85)
        at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
        at org.apache.spark.sql.delta.files.DeltaFileFormatWriter$.$anonfun$executeTask$1(DeltaFileFormatWriter.scala:430)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
        at org.apache.spark.sql.delta.files.DeltaFileFormatWriter$.executeTask(DeltaFileFormatWriter.scala:437)
        ... 12 more
```

**Comment by sf11349** [comment] 2024-05-08 07:57
Hello. Thanks for bringing this to my attention. 
I was not able to reproduce the error. See my run below. 
Possibly an access or authorisation issue or the way the docker has been setup. 

2024-05-08 08:46:03 INFO:root:START the ETL pipeline run
2024-05-08 08:46:03 
2024-05-08 08:46:03 INFO:root:Initiating Sparks instance
24/05/07 22:09:39 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
2024-05-08 08:46:06 :: loading settings :: url = jar:file:/usr/local/spark-3.5.0-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
2024-05-08T07:46:06.954003326Z Ivy Default Cache set to: /home/jovyan/.ivy2/cache
2024-05-08 08:46:06 The jars for the packages stored in: /home/jovyan/.ivy2/jars
2024-05-08 08:46:06 io.delta#delta-spark_2.12 added as a dependency
2024-05-08 08:46:06 :: resolving dependencies :: org.apache.spark#spark-submit-parent-81b75795-b71d-4e2b-8a1c-0d78c944a9fa;1.0
2024-05-08 08:46:06     confs: [default]
2024-05-08 08:46:07     found io.delta#delta-spark_2.12;3.1.0 in central
2024-05-08 08:46:07     found io.delta#delta-storage;3.1.0 in central
2024-05-08 08:46:07     found org.antlr#antlr4-runtime;4.9.3 in central
2024-05-08 08:46:07 :: resolution report :: resolve 417ms :: artifacts dl 15ms
2024-05-08 08:46:07     :: modules in use:
2024-05-08 08:46:07     io.delta#delta-spark_2.12;3.1.0 from central in [default]
2024-05-08 08:46:07     io.delta#delta-storage;3.1.0 from central in [default]
2024-05-08 08:46:07     org.antlr#antlr4-runtime;4.9.3 from central in [default]
2024-05-08 08:46:07     ---------------------------------------------------------------------
2024-05-08 08:46:07     |                  |            modules            ||   artifacts   |
2024-05-08 08:46:07     |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
2024-05-08 08:46:07     ---------------------------------------------------------------------
2024-05-08 08:46:07     |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
2024-05-08 08:46:07     ---------------------------------------------------------------------
2024-05-08 08:46:07 :: retrieving :: org.apache.spark#spark-submit-parent-81b75795-b71d-4e2b-8a1c-0d78c944a9fa
2024-05-08 08:46:07     confs: [default]
2024-05-08 08:46:07     0 artifacts copied, 3 already retrieved (0kB/13ms)
2024-05-08 08:46:07 24/05/08 07:46:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-05-08 08:46:08 Setting default log level to "WARN".
2024-05-08 08:46:08 To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2024-05-08 08:46:11 INFO:root:Sparks instance ready
2024-05-08 08:46:11 
2024-05-08 08:46:11 INFO:root: Extracting from source ....
2024-05-08 08:46:18 +-------+----------+--------+--------+-----+
2024-05-08 08:46:18 |OrderID|CustomerID| Product|Quantity|Price|
2024-05-08 08:46:18 +-------+----------+--------+--------+-----+
2024-05-08 08:46:18 |   1001|      C101|Widget A|      10| 25.5|
2024-05-08 08:46:18 |   1002|      C102|Widget B|       5|18.75|
2024-05-08 08:46:18 |   1003|      C103|Widget A|       8| 25.5|
2024-05-08 08:46:18 |   1004|      C104|Widget C|      12| 30.0|
2024-05-08 08:46:18 |   1005|      C105|Widget B|       3|18.75|
2024-05-08 08:46:18 +-------+----------+--------+--------+-----+
2024-05-08 08:46:18 
2024-05-08 08:46:18 INFO:root: - Number of records extracted: 5
2024-05-08 08:46:18 INFO:root: Finished extracting from source. 
2024-05-08 08:46:18 
2024-05-08 08:46:18 INFO:root: Transforming ....
2024-05-08 08:46:19 +-------+----------+--------+--------+-----+----------------+
2024-05-08 08:46:19 |OrderID|CustomerID| Product|Quantity|Price|TotalOrderAmount|
2024-05-08 08:46:19 +-------+----------+--------+--------+-----+----------------+
2024-05-08 08:46:19 |   1001|      C101|Widget A|      10| 25.5|           255.0|
2024-05-08 08:46:19 |   1002|      C102|Widget B|       5|18.75|           93.75|
2024-05-08 08:46:19 |   1003|      C103|Widget A|       8| 25.5|           204.0|
2024-05-08 08:46:19 |   1004|      C104|Widget C|      12| 30.0|           360.0|
2024-05-08 08:46:19 |   1005|      C105|Widget B|       3|18.75|           56.25|
2024-05-08 08:46:19 +-------+----------+--------+--------+-----+----------------+
2024-05-08 08:46:19 
2024-05-08 08:46:19 INFO:root: - Number of records transformed: 5
2024-05-08 08:46:19 INFO:root: Finished transformation. 
2024-05-08 08:46:19 
2024-05-08 08:46:19 INFO:root: Loading to Delta Table ....
2024-05-08 08:46:22 24/05/08 07:46:22 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
2024-05-08 08:46:34 INFO:root: - Table CustomerOrders loaded. Number of records: 5
2024-05-08 08:46:34 INFO:root: Finished loading. 
2024-05-08 08:46:34 
2024-05-08 08:46:34 INFO:root:FINISHED successfully the ETL pipeline run
2024-05-08 08:46:34 INFO:py4j.clientserver:Closing down clientserver connection

**Comment by pontusvision** [comment] 2024-05-08 09:11
Docker has been configured correctly; it is used by several other containers successfully.   We are using Rancher desktop and running this from a WSL ubuntu 22.04 instance ; here are the details:
```
$ which docker
/mnt/c/Program Files/Rancher Desktop/resources/resources/linux/bin//docker

$ docker --version
Docker version 25.0.4-rd, build c4cd0a9
```
OS: Ubuntu 22.04 - WSL:
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by sf11349** [comment] 2024-05-08 16:55
Updated the destination Delta Table name, because the OS (UBUNTU) was trying to generate a folder with the same name.

2024-05-08 17:48:36 INFO:root:START the ETL pipeline run
2024-05-08 17:48:36 
2024-05-08 17:48:36 INFO:root:Initiating Sparks instance
2024-05-08 17:48:39 :: loading settings :: url = jar:file:/usr/local/spark-3.5.0-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
2024-05-08 17:48:39 Ivy Default Cache set to: /home/jovyan/.ivy2/cache
2024-05-08 17:48:39 The jars for the packages stored in: /home/jovyan/.ivy2/jars
2024-05-08 17:48:39 io.delta#delta-spark_2.12 added as a dependency
2024-05-08 17:48:39 :: resolving dependencies :: org.apache.spark#spark-submit-parent-2d126bd2-8fcf-4a50-821c-f6e2a05e3c13;1.0
2024-05-08 17:48:39     confs: [default]
2024-05-08 17:48:40     found io.delta#delta-spark_2.12;3.1.0 in central
2024-05-08 17:48:40     found io.delta#delta-storage;3.1.0 in central
2024-05-08 17:48:41     found org.antlr#antlr4-runtime;4.9.3 in central
2024-05-08 17:48:41 downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
2024-05-08 17:48:42     [SUCCESSFUL ] io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar (823ms)
2024-05-08 17:48:42 downloading https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar ...
2024-05-08 17:48:42     [SUCCESSFUL ] io.delta#delta-storage;3.1.0!delta-storage.jar (31ms)
2024-05-08 17:48:42 downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
2024-05-08 17:48:42     [SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (82ms)
2024-05-08 17:48:42 :: resolution report :: resolve 2544ms :: artifacts dl 944ms
2024-05-08 17:48:42     :: modules in use:
2024-05-08 17:48:42     io.delta#delta-spark_2.12;3.1.0 from central in [default]
2024-05-08 17:48:42     io.delta#delta-storage;3.1.0 from central in [default]
2024-05-08 17:48:42     org.antlr#antlr4-runtime;4.9.3 from central in [default]
2024-05-08 17:48:42     ---------------------------------------------------------------------
2024-05-08 17:48:42     |                  |            modules            ||   artifacts   |
2024-05-08 17:48:42     |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
2024-05-08 17:48:42     ---------------------------------------------------------------------
2024-05-08 17:48:42     |      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
2024-05-08 17:48:42     ---------------------------------------------------------------------
2024-05-08 17:48:42 :: retrieving :: org.apache.spark#spark-submit-parent-2d126bd2-8fcf-4a50-821c-f6e2a05e3c13
2024-05-08 17:48:42     confs: [default]
2024-05-08 17:48:42     3 artifacts copied, 0 already retrieved (5727kB/22ms)
2024-05-08 17:48:43 24/05/08 16:48:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-05-08 17:48:43 Setting default log level to "WARN".
2024-05-08 17:48:43 To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2024-05-08 17:48:46 INFO:root:Sparks instance ready
2024-05-08 17:48:46 
2024-05-08 17:48:46 INFO:root: Extracting from source ....
2024-05-08 17:48:54 +-------+----------+--------+--------+-----+
2024-05-08 17:48:54 |OrderID|CustomerID| Product|Quantity|Price|
2024-05-08 17:48:54 +-------+----------+--------+--------+-----+
2024-05-08 17:48:54 |   1001|      C101|Widget A|      10| 25.5|
2024-05-08 17:48:54 |   1002|      C102|Widget B|       5|18.75|
2024-05-08 17:48:54 |   1003|      C103|Widget A|       8| 25.5|
2024-05-08 17:48:54 |   1004|      C104|Widget C|      12| 30.0|
2024-05-08 17:48:54 |   1005|      C105|Widget B|       3|18.75|
2024-05-08 17:48:54 +-------+----------+--------+--------+-----+
2024-05-08 17:48:54 
2024-05-08 17:48:54 INFO:root: - Number of records extracted: 5
2024-05-08 17:48:54 INFO:root: Finished extracting from source. 
2024-05-08 17:48:54 
2024-05-08 17:48:54 INFO:root: Transforming ....
2024-05-08 17:48:54 +-------+----------+--------+--------+-----+----------------+
2024-05-08 17:48:54 |OrderID|CustomerID| Product|Quantity|Price|TotalOrderAmount|
2024-05-08 17:48:54 +-------+----------+--------+--------+-----+----------------+
2024-05-08 17:48:54 |   1001|      C101|Widget A|      10| 25.5|           255.0|
2024-05-08 17:48:54 |   1002|      C102|Widget B|       5|18.75|           93.75|
2024-05-08 17:48:54 |   1003|      C103|Widget A|       8| 25.5|           204.0|
2024-05-08 17:48:54 |   1004|      C104|Widget C|      12| 30.0|           360.0|
2024-05-08 17:48:54 |   1005|      C105|Widget B|       3|18.75|           56.25|
2024-05-08 17:48:54 +-------+----------+--------+--------+-----+----------------+
2024-05-08 17:48:54 
2024-05-08 17:48:54 INFO:root: - Number of records transformed: 5
2024-05-08 17:48:54 INFO:root: Finished transformation. 
2024-05-08 17:48:54 
2024-05-08 17:48:54 INFO:root: Loading to Delta Table ....
24/05/08 16:49:01 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
2024-05-08 17:49:06 INFO:root: - Table shawan_data/sink/CustomerOrders loaded. Number of records: 5
2024-05-08 17:49:06 INFO:root: Finished loading. 
2024-05-08 17:49:06 
2024-05-08 17:49:06 INFO:root:FINISHED successfully the ETL pipeline run
2024-05-08 17:49:06 INFO:py4j.clientserver:Closing down clientserver connection

**Closed** 2024-05-08 17:17 UTC

**Comment by pontusvision** [comment] 2024-05-09 07:11
I'm really sorry you did not persist with the problem.  As the error message indicated, this was a permissions problem:
```
Caused by: java.io.IOException: Mkdirs failed to create file:/sf_de_assignment/data/sink/CustomerOrders/Product=Widget A (exists=false, cwd=file:/sf_de_assignment)
```

So, a simple change to your docker file would have resolved this issue.  Thank you for your time.
